name: React App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12.18.2
      - name: Install React
        uses: npx create-react-app react-base-app
      - name: Initiate React
        uses: npm start
      - name: Install Surge
        run: npm install -g surge
      - name: Run surge
        run: surge ./ bootcamp_setup_ziakhan.surge.sh --token ${{ secrets.TOKEN }}
